global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'gitops-lab'
    environment: 'production'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
        labels:
          service: 'nginx'
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          service: 'node-exporter'
          host: 'devops-lab'
